# Offense count: 16
Lint/UselessAssignment:
  Exclude:
    - 'lib/lookup_service_helper.rb'

# Offense count: 1
# Configuration parameters: EnforcedStyle.
# SupportedStyles: snake_case, camelCase
Naming/VariableName:
  Exclude:
    - 'lib/lookup_service_helper.rb'

# Offense count: 36
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 147
